"""create wishes table

Revision ID: 6b2db7809e79
Revises:
Create Date: 2025-10-19 22:20:01.688907

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b2db7809e79"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wishes",
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("link", sa.String(length=200), nullable=True),
        sa.Column("price_estimate", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("notes", sa.String(length=500), nullable=True),
        sa.Column("category", sa.String(length=30), nullable=True),
        sa.CheckConstraint("price_estimate >= 0", name="ck_wishes_price_non_negative"),
        sa.PrimaryKeyConstraint("owner", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("wishes")
    # ### end Alembic commands ###
